In [1]:
import torch
from torch import nn
import torch.optim as optim

In [2]:
net = nn.Sequential(nn.Linear(1, 2, bias=False), 
                    nn.Tanh(), 
                    nn.Linear(2, 1, bias=False))

learning_rate = 0.1
optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate)

In [3]:
# init network weights to be 0.
nn.init.constant_(net[0].weight, 0.)
nn.init.constant_(net[2].weight, 0.)

print('--- layer 1 weights and biases')
print(net[0].weight)

print('--- layer 2 weights and biases')
print(net[2].weight)

--- layer 1 weights and biases
Parameter containing:
tensor([[0.],
        [0.]], requires_grad=True)
--- layer 2 weights and biases
Parameter containing:
tensor([[0., 0.]], requires_grad=True)


In [4]:
Niters = 100

for j in range(Niters):
    
    x = torch.rand(1)
    out = net(x)
    
    optimizer.zero_grad() 
    out.backward() 
    optimizer.step()

In [5]:
print('--- layer 1 weights and biases')
print(net[0].weight)

print('--- layer 2 weights and biases')
print(net[2].weight)

--- layer 1 weights and biases
Parameter containing:
tensor([[0.],
        [0.]], requires_grad=True)
--- layer 2 weights and biases
Parameter containing:
tensor([[0., 0.]], requires_grad=True)


In [6]:
import torch
from torch import nn
import torch.optim as optim

# --- define network structure --- 
net = nn.Sequential(nn.Linear(1, 2, bias=False), 
                    nn.Tanh(), 
                    nn.Linear(2, 1, bias=False))

learning_rate = 0.1
optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate)

# --- init network weights to be 0. --- 
nn.init.constant_(net[0].weight, 0.3)
nn.init.constant_(net[2].weight, 0.5)

print('--- layer 1 weights and biases')
print(net[0].weight)

print('--- layer 2 weights and biases')
print(net[2].weight)

# --- training loop --- 
Niters = 100
for j in range(Niters):
    x = torch.rand(1)
    out = net(x)
    
    optimizer.zero_grad() 
    out.backward() 
    optimizer.step()

# --- check network weights again --- 
print('--- layer 1 weights and biases')
print(net[0].weight)

print('--- layer 2 weights and biases')
print(net[2].weight)

--- layer 1 weights and biases
Parameter containing:
tensor([[0.3000],
        [0.3000]], requires_grad=True)
--- layer 2 weights and biases
Parameter containing:
tensor([[0.5000, 0.5000]], requires_grad=True)
--- layer 1 weights and biases
Parameter containing:
tensor([[-2.7873],
        [-2.7873]], requires_grad=True)
--- layer 2 weights and biases
Parameter containing:
tensor([[4.1369, 4.1369]], requires_grad=True)
